language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: XLXqVNLHMAapIyO976OWYyzAkb8cWxN2lWTvXEYqI7Y9VYgfvo75/SJrqpi95GN+7ZG61ewaYHZLoks2MjhM2PDdnxXzJQHyIEBP6Kt4Codshq6ijyN9bCULHl9lju5ddjuwlgtGWn2V0yVCWOKmC7xn0zaXPnxgtO1dDJFr1XAjxcA8M7JFRhxyS0soQVSOlSoga1YB8lk5eEKkaF9xs5zX5LUy6AKrib+gknCrlrvT7tK55Xcz0yNmeBsP8BEY2RCP48HrFQ+P3EtOj/t37hG9UxeBn+SmrIEFKW6A2FCgTsgrgqC9QhIo/pJXK7rAUPVIupfXEf2klBpcz1ZJqht7cISix3b6+RM+HVz630mn6y4hCqL76U5ctVu0IGcv9zIv/gvvVNRoxiDxdIONDzwBOmCyTtfjw+epmXN2doPL5KvFhq5zFnkKtWuDqUeIWDFWw4p9y5n0AhOS0fNAcVHHOXpmAwDxekrbYrFt40sRKot5U/2+YUPOqt3g9D4lz9hEGZAwj8LeWK4A5GwKX8rXpaX2VzicWCkdeiivUOHvTE7SZst8nxN89RKBs9jMn0cdN/NOciRz0RoR9OBx3bhXjZpaFnnU5vhA3N/0Z6kQmB6mgh3y2D4z903yxYZHZFY3EbuygNAAReYXDyvFjEfRkb1awMmEabfA6iIXAZY=
  app: cryptic-earth-98692
  on:
    repo: CraigPounds/react-hot-cold
